# -*- coding: utf-8 -*-
"""ChatGPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/140xxcr3GaQrmSopNZEDiOMk8FKvtUAK0
"""

!pip install openai

# import openai
# sk-
# # Set up your OpenAI API key
# openai.api_key = 'sk-proj-8k4gK'

import openai
import time

# Set your OpenAI API key
openai.api_key = "sk-proj-8k4gK"

def chat_with_gpt(prompt):
    try:
        response = openai.chat.completions.create(
            model="gpt-3.5-turbo",  # Or 'gpt-4' if available
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt}
            ],
            max_tokens=150,
            temperature=0.7,  # Controls the creativity
        )
        return response['choices'][0]['message']['content']
    except Exception as e:
        print(f"An error occurred: {e}")
        return "Sorry, I couldn't process your request."

if __name__ == "__main__":
    print("ChatGPT Bot is ready. Type 'exit' to stop.")

    while True:
        user_input = input("You: ")
        if user_input.lower() == 'exit':
            break

        # Get the chatbot's response
        response = chat_with_gpt(user_input)
        print("Bot:", response)



!pip install google-auth-httplib2 google-auth-oauthlib

!pip install google-cloud-dialogflow
import os
from google.oauth2 import service_account
from google.cloud import dialogflow_v2 as dialogflow

def detect_intent_text(project_id, session_id, text, language_code):
    """Detects the intent from the text input."""

    session_client = dialogflow.SessionsClient()

    session = session_client.session_path(project_id, session_id)

    text_input = dialogflow.TextInput(text=text, language_code=language_code)
    query_input = dialogflow.QueryInput(text=text_input)

    response = session_client.detect_intent(session=session, query_input=query_input)

    return response.query_result.fulfillment_text

def main():
    project_id = "your-project-id"
    session_id = "your-session-id"
    language_code = "en-US"

    while True:
        text = input("You: ")
        response = detect_intent_text(project_id, session_id, text, language_code)
        print("Bot:", response)

if __name__ == "__main__":
    main()